// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SklepSportowy.Models;

#nullable disable

namespace SklepSportowy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230124145909_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SklepSportowy.Models.Firma", b =>
                {
                    b.Property<int>("FirmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FirmaId"));

                    b.Property<DateTime>("DzienDodania")
                        .HasColumnType("datetime2");

                    b.Property<string>("NazwaFirmy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SprzetId")
                        .HasColumnType("int");

                    b.Property<int?>("SprzetSportowyId")
                        .HasColumnType("int");

                    b.HasKey("FirmaId");

                    b.HasIndex("SprzetSportowyId");

                    b.ToTable("Firma");
                });

            modelBuilder.Entity("SklepSportowy.Models.SprzetSportowy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Cena")
                        .HasColumnType("float");

                    b.Property<string>("ModelSprzetu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NazwaSprzetu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SprzetSportowy");
                });

            modelBuilder.Entity("SklepSportowy.Models.Firma", b =>
                {
                    b.HasOne("SklepSportowy.Models.SprzetSportowy", "SprzetSportowy")
                        .WithMany("Firmy")
                        .HasForeignKey("SprzetSportowyId");

                    b.Navigation("SprzetSportowy");
                });

            modelBuilder.Entity("SklepSportowy.Models.SprzetSportowy", b =>
                {
                    b.Navigation("Firmy");
                });
#pragma warning restore 612, 618
        }
    }
}
