// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SklepSportowy.Models;

#nullable disable

namespace SklepSportowy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SklepSportowy.Models.Dane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumerTelefonu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dane");
                });

            modelBuilder.Entity("SklepSportowy.Models.Firma", b =>
                {
                    b.Property<int>("FirmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FirmaId"));

                    b.Property<DateTime>("DzienDodania")
                        .HasColumnType("datetime2");

                    b.Property<string>("NazwaFirmy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SprzetId")
                        .HasColumnType("int");

                    b.Property<int?>("SprzetSportowyId")
                        .HasColumnType("int");

                    b.HasKey("FirmaId");

                    b.HasIndex("SprzetSportowyId");

                    b.ToTable("Firma");
                });

            modelBuilder.Entity("SklepSportowy.Models.Promocja", b =>
                {
                    b.Property<int>("PromocjaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromocjaId"));

                    b.Property<string>("NazwaPromocji")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SprzetId")
                        .HasColumnType("int");

                    b.Property<int?>("SprzetSportowyId")
                        .HasColumnType("int");

                    b.Property<int>("WartoscPromocji")
                        .HasColumnType("int");

                    b.HasKey("PromocjaId");

                    b.HasIndex("SprzetSportowyId");

                    b.ToTable("Promocja");
                });

            modelBuilder.Entity("SklepSportowy.Models.SprzetSportowy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Cena")
                        .HasColumnType("float");

                    b.Property<string>("ModelSprzetu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NazwaSprzetu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SprzetSportowy");
                });

            modelBuilder.Entity("SklepSportowy.Models.Firma", b =>
                {
                    b.HasOne("SklepSportowy.Models.SprzetSportowy", "SprzetSportowy")
                        .WithMany("Firmy")
                        .HasForeignKey("SprzetSportowyId");

                    b.Navigation("SprzetSportowy");
                });

            modelBuilder.Entity("SklepSportowy.Models.Promocja", b =>
                {
                    b.HasOne("SklepSportowy.Models.SprzetSportowy", "SprzetSportowy")
                        .WithMany("Promocje")
                        .HasForeignKey("SprzetSportowyId");

                    b.Navigation("SprzetSportowy");
                });

            modelBuilder.Entity("SklepSportowy.Models.SprzetSportowy", b =>
                {
                    b.Navigation("Firmy");

                    b.Navigation("Promocje");
                });
#pragma warning restore 612, 618
        }
    }
}
